/// <reference types="astro/client" />

/**
 * Ambient modules the package uses inside an Astro build. `astro:env` is
 * generated by Astro from the schema the integration registers;
 * `virtual:bilboost/options` is the integration's own Vite plugin;
 * `cloudflare:workers` exists only inside the Worker runtime.
 */

declare module "astro:env/server" {
  export const BILBOOST_API_BASE: string;
  export const BILBOOST_READ_TOKEN: string;
  export const BILBOOST_WEBHOOK_SECRET: string | undefined;
  export const BILBOOST_WEBHOOK_SECRET_NEXT: string | undefined;
}

declare module "astro:env/client" {
  export const PUBLIC_TURNSTILE_SITE_KEY: string | undefined;
}

declare module "virtual:bilboost/options" {
  const options: import("./options.ts").ResolvedOptions;
  export default options;
}

declare module "cloudflare:workers" {
  export const cache: {
    purge(options: {
      tags?: string[];
      pathPrefixes?: string[];
      purgeEverything?: boolean;
    }): Promise<{ success: boolean; errors: { message: string; code?: number }[] }>;
  };
}
